# Generated by Django 4.0.3 on 2022-09-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Africa', 'Africa'), ('England', 'England'), ('Dubai', 'Dubai'), ('Canada', 'Canada'), ('UK', 'UK'), ('USA', 'USA')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
