# Generated by Django 4.0.3 on 2022-09-09 06:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_country_customuser_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=150)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('blogtype', models.CharField(choices=[('Travel', 'Travel'), ('Sports', 'Sports'), ('Health and fitness', 'Health and fitness'), ('Science', 'Science'), ('Lifestyle', 'Lifestyle'), ('Technologies', 'Technologies'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Photography', 'Photography')], max_length=200, null=True)),
            ],
        ),
    ]
