# Generated by Django 4.0.3 on 2022-09-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_blog_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogtype',
            field=models.CharField(blank=True, choices=[('Travel', 'Travel'), ('Sports', 'Sports'), ('Health and fitness', 'Health and fitness'), ('Science', 'Science'), ('Lifestyle', 'Lifestyle'), ('Technologies', 'Technologies'), ('Food', 'Food'), ('Fashion', 'Fashion'), ('Photography', 'Photography')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
