# Generated by Django 4.0.3 on 2022-09-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_blog_blogtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
