# Generated by Django 4.0.3 on 2022-09-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customuser_is_active_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, choices=[('India', 'India'), ('Africa', 'Africa'), ('England', 'England'), ('Dubai', 'Dubai'), ('Canada', 'Canada'), ('UK', 'UK'), ('USA', 'USA')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default=0, max_length=200),
            preserve_default=False,
        ),
    ]
